<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>getRatios</name>
  <uuid>c79a5e36-9d0f-4d81-826b-4412a112307f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the product ratios of Components ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
