<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Check how many ratios are below a certain ratio</name>
  <uuid>a93b9b6e-e6b2-42a9-ba69-b42dd0d7cf36</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
 set num to the number of numbers in 'Get ratios for core components' - 2;
if
	there are more than num numbers in 'Get ratios for core components' where each number is less than the product ratio of 'Core Components',
then
	set decision to "scrap" ;
else
    set decision to "don't scrap" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
