<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Merger</name>
  <uuid>6cb36832-634b-4588-b46a-fad66ec9a4b0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set  to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
