<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>MOVE</name>
  <uuid>ead722f1-cc3a-4a9d-b3ab-5779bdfcd121</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each store called item, in StoreList:
-for each storedetail called storeitem, in the storedetails of item:

-define avar as a new RebalanceDecision where 
	the from is "dont know yet" , 
	the amount is 4 , 
	the item is 123 

-set the from of avar to the storeid of item
-add avar to decision;

]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
