<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>OrgInventoryByStore</name>
  <uuid>de87802c-3a9a-46fb-a124-ac057948aeb3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
