<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>REFINE</name>
  <uuid>ade2d7f3-fe0a-46cb-8f46-10f790fe3d22</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each ReplenishDecision called item, in RepDecision
if the amount of item > 0
then add item to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
