<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Max</name>
  <uuid>84faf9ff-6a48-41d0-96ad-57be569e10b7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the maximum FindingMaxArray;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
