<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Grand Totals</name>
  <uuid>075cc265-e0e3-412c-849e-c2e965e485fd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each row called item, in the rows of 'Stock Table'
if
  the ids of 'Core Components' contain the id of item
then
  add the grand total of item to the core totals of decision;
else
  add the grand total of item to the other totals of decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
