<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>FindingMax</name>
  <uuid>f249203c-621a-4d3a-8e44-1e7fbf8912f8</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each row called itema, in the rows of StockTable:
-define itembs as all repids in the repids of repcomponents, where the id is the id of itema
-for each repid called itemb, in itembs:
-add the grand total of itema / the ratio of itemb to decision;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
